#' @details
#' SMOTENC extends SMOTE to handle data sets with a mix of numeric and
#' categorical predictors. For each minority class example, new synthetic
#' examples are generated by interpolating between the example and its nearest
#' neighbors using Gower's distance. Numeric features are interpolated
#' continuously; categorical features take the most common value among the
#' neighbors. The number of new examples generated is controlled by
#' `over_ratio`.
