#' @details
#' KMeans-SMOTE combines k-means clustering with SMOTE to avoid generating
#' synthetic points in regions where the minority class is not actually
#' present. It works in three stages:
#'
#' 1. The predictor space of the whole data set is clustered with
#'    [stats::kmeans()] into `num_clusters` clusters.
#' 2. Each cluster is either kept or filtered out. A cluster is kept for a
#'    given minority class if the ratio of that class's observations to all
#'    other observations in the cluster is at least
#'    `cluster_balance_threshold`, and if the cluster contains more than
#'    `neighbors` observations of that class so that interpolation is
#'    possible.
#' 3. The synthetic points are distributed over the kept clusters according to
#'    how sparse each cluster is. The sparsity of a cluster is
#'    `mean_pairwise_distance ^ density_exponent / n`, where `n` is the number
#'    of minority observations in the cluster. Sparser clusters receive more
#'    points. Within each cluster the points are then generated by ordinary
#'    SMOTE interpolation, using only that cluster's observations as
#'    neighbors.
#'
#' Filtering on cluster balance keeps synthetic points away from
#' majority-dominated regions, and the density weighting counteracts
#' within-class imbalance rather than only between-class imbalance.
#'
#' The clustering is done once on all observations, so in a multi-class
#' problem every minority class shares the same clusters; only the filtering
#' and weighting are done per class. Note also that k-means always uses
#' Euclidean distance. The `distance` argument affects the nearest-neighbor
#' search used for interpolation and the sparsity calculation, not the
#' clustering itself.
