#' @details
#' SMOTEN is a variant of SMOTE designed for data sets where all predictors are
#' categorical (nominal). Since standard SMOTE relies on interpolation in
#' continuous space, it cannot be applied to categorical features directly.
#' SMOTEN instead uses the Value Difference Metric (VDM) to measure the distance
#' between observations. For each minority class example, new synthetic examples
#' are generated by taking the most common value of each predictor among its
#' nearest neighbors. The number of new examples generated is controlled by
#' `over_ratio`.
